"""conversation_related_tables

Revision ID: cfc7f3a34254
Revises: 0597e9d3b1ab
Create Date: 2026-02-02 09:13:17.308432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc7f3a34254'
down_revision: Union[str, Sequence[str], None] = '0597e9d3b1ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CONVERSATION',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED_SUCCESS', 'COMPLETED_ERROR', 'TERMINATED_OFF_TOPIC', 'TERMINATED_MAX_TURNS', name='conversationstatus'), nullable=False),
    sa.Column('intent', sa.Enum('EVALUATE_PURCHASE', 'ADD_TRANSACTION', 'GET_SPENDING_SUMMARY', 'UNKNOWN', name='intenttype'), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('collected_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CONVERSATION_conversation_id'), 'CONVERSATION', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_CONVERSATION_user_id'), 'CONVERSATION', ['user_id'], unique=False)
    op.create_table('CONVERSATION_MESSAGE',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='conversationrole'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['CONVERSATION.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CONVERSATION_MESSAGE_external_id'), 'CONVERSATION_MESSAGE', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CONVERSATION_MESSAGE_external_id'), table_name='CONVERSATION_MESSAGE')
    op.drop_table('CONVERSATION_MESSAGE')
    op.drop_index(op.f('ix_CONVERSATION_user_id'), table_name='CONVERSATION')
    op.drop_index(op.f('ix_CONVERSATION_conversation_id'), table_name='CONVERSATION')
    op.drop_table('CONVERSATION')
    # ### end Alembic commands ###
