"""alter_financial-snapshot-columns

Revision ID: 0597e9d3b1ab
Revises: 79b47cd7af43
Create Date: 2026-01-29 18:14:32.046282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0597e9d3b1ab'
down_revision: Union[str, Sequence[str], None] = '79b47cd7af43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FINANCIAL_PERIOD_SNAPSHOT', sa.Column('categories_spends', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")))
    op.add_column('FINANCIAL_PERIOD_SNAPSHOT', sa.Column('budgets_statuses', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")))
    op.drop_column('FINANCIAL_PERIOD_SNAPSHOT', 'category_spend')
    op.drop_column('FINANCIAL_PERIOD_SNAPSHOT', 'budget_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FINANCIAL_PERIOD_SNAPSHOT', sa.Column('budget_status', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")))
    op.add_column('FINANCIAL_PERIOD_SNAPSHOT', sa.Column('category_spend', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")))
    op.drop_column('FINANCIAL_PERIOD_SNAPSHOT', 'budgets_statuses')
    op.drop_column('FINANCIAL_PERIOD_SNAPSHOT', 'categories_spends')
    # ### end Alembic commands ###
