"""initial_setup

Revision ID: ac3c23337782
Revises:
Create Date: 2026-01-13 08:07:04.986395

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ac3c23337782"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "USER",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("default_currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index(op.f("ix_USER_email"), "USER", ["email"], unique=True)
    op.create_table(
        "CATEGORY",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_discretionary", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["USER.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index(op.f("ix_CATEGORY_user_id"), "CATEGORY", ["user_id"], unique=False)
    op.create_index("ix_category_user_name", "CATEGORY", ["user_id", "name"], unique=True)
    op.create_table(
        "FINANCIAL_PERIOD_SNAPSHOT",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.Enum("WEEKLY", "MONTHLY", "YEARLY", name="periodenum"), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("total_income", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("total_outcome", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("savings", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("savings_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("category_spend", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("budget_status", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["USER.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index(
        op.f("ix_FINANCIAL_PERIOD_SNAPSHOT_user_id"), "FINANCIAL_PERIOD_SNAPSHOT", ["user_id"], unique=False
    )
    op.create_index(
        "ix_financial_period_snapshot_user_period",
        "FINANCIAL_PERIOD_SNAPSHOT",
        ["user_id", "period", "start_date"],
        unique=False,
    )
    op.create_table(
        "RAW_TRANSACTION",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("type", sa.Enum("DEBIT", "CREDIT", name="transactiontype"), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("raw_category", sa.String(length=100), nullable=True),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["USER.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index(op.f("ix_RAW_TRANSACTION_date"), "RAW_TRANSACTION", ["date"], unique=False)
    op.create_index(op.f("ix_RAW_TRANSACTION_user_id"), "RAW_TRANSACTION", ["user_id"], unique=False)
    op.create_index("ix_raw_transaction_user_date", "RAW_TRANSACTION", ["user_id", "date"], unique=False)
    op.create_table(
        "BUDGET_THRESHOLD",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.Enum("WEEKLY", "MONTHLY", "YEARLY", name="periodenum"), nullable=False),
        sa.Column("limit_amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "source", sa.Enum("USER_DEFINED", "SYSTEM_SUGGESTED", name="budgedthresholdsourceenum"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["CATEGORY.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["USER.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index(op.f("ix_BUDGET_THRESHOLD_category_id"), "BUDGET_THRESHOLD", ["category_id"], unique=False)
    op.create_index(op.f("ix_BUDGET_THRESHOLD_user_id"), "BUDGET_THRESHOLD", ["user_id"], unique=False)
    op.create_index(
        "ix_budget_threshold_user_category_period",
        "BUDGET_THRESHOLD",
        ["user_id", "category_id", "period"],
        unique=False,
    )
    op.create_table(
        "NORMALIZED_TRANSACTION",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum("DEBIT", "CREDIT", name="transactiontype"), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("raw_category", sa.String(length=100), nullable=False),
        sa.Column("predicted_category", sa.String(length=100), nullable=False),
        sa.Column("category_confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("resolved_category", sa.String(length=100), nullable=False),
        sa.Column(
            "recurrence_status", sa.Enum("UNKNOWN", "INFERRED", "CONFIRMED", name="recurrencestatus"), nullable=False
        ),
        sa.Column("recurrence_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("recurrence_period", sa.Enum("WEEKLY", "MONTHLY", "YEARLY", name="periodenum"), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("raw_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("financial_period_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["CATEGORY.id"],
        ),
        sa.ForeignKeyConstraint(
            ["financial_period_snapshot_id"],
            ["FINANCIAL_PERIOD_SNAPSHOT.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_transaction_id"],
            ["RAW_TRANSACTION.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["USER.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
        sa.UniqueConstraint("raw_transaction_id"),
    )
    op.create_index(
        op.f("ix_NORMALIZED_TRANSACTION_category_id"), "NORMALIZED_TRANSACTION", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_NORMALIZED_TRANSACTION_date"), "NORMALIZED_TRANSACTION", ["date"], unique=False)
    op.create_index(
        op.f("ix_NORMALIZED_TRANSACTION_financial_period_snapshot_id"),
        "NORMALIZED_TRANSACTION",
        ["financial_period_snapshot_id"],
        unique=False,
    )
    op.create_index(op.f("ix_NORMALIZED_TRANSACTION_user_id"), "NORMALIZED_TRANSACTION", ["user_id"], unique=False)
    op.create_index("ix_normalized_transaction_user_date", "NORMALIZED_TRANSACTION", ["user_id", "date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_normalized_transaction_user_date", table_name="NORMALIZED_TRANSACTION")
    op.drop_index(op.f("ix_NORMALIZED_TRANSACTION_user_id"), table_name="NORMALIZED_TRANSACTION")
    op.drop_index(op.f("ix_NORMALIZED_TRANSACTION_financial_period_snapshot_id"), table_name="NORMALIZED_TRANSACTION")
    op.drop_index(op.f("ix_NORMALIZED_TRANSACTION_date"), table_name="NORMALIZED_TRANSACTION")
    op.drop_index(op.f("ix_NORMALIZED_TRANSACTION_category_id"), table_name="NORMALIZED_TRANSACTION")
    op.drop_table("NORMALIZED_TRANSACTION")
    op.drop_index("ix_budget_threshold_user_category_period", table_name="BUDGET_THRESHOLD")
    op.drop_index(op.f("ix_BUDGET_THRESHOLD_user_id"), table_name="BUDGET_THRESHOLD")
    op.drop_index(op.f("ix_BUDGET_THRESHOLD_category_id"), table_name="BUDGET_THRESHOLD")
    op.drop_table("BUDGET_THRESHOLD")
    op.drop_index("ix_raw_transaction_user_date", table_name="RAW_TRANSACTION")
    op.drop_index(op.f("ix_RAW_TRANSACTION_user_id"), table_name="RAW_TRANSACTION")
    op.drop_index(op.f("ix_RAW_TRANSACTION_date"), table_name="RAW_TRANSACTION")
    op.drop_table("RAW_TRANSACTION")
    op.drop_index("ix_financial_period_snapshot_user_period", table_name="FINANCIAL_PERIOD_SNAPSHOT")
    op.drop_index(op.f("ix_FINANCIAL_PERIOD_SNAPSHOT_user_id"), table_name="FINANCIAL_PERIOD_SNAPSHOT")
    op.drop_table("FINANCIAL_PERIOD_SNAPSHOT")
    op.drop_index("ix_category_user_name", table_name="CATEGORY")
    op.drop_index(op.f("ix_CATEGORY_user_id"), table_name="CATEGORY")
    op.drop_table("CATEGORY")
    op.drop_index(op.f("ix_USER_email"), table_name="USER")
    op.drop_table("USER")
    # ### end Alembic commands ###
