"""alter-normalized_transactions-make-reccurance_period-nullable

Revision ID: d7ebcb5331dc
Revises: ac3c23337782
Create Date: 2026-01-26 21:32:17.651105

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d7ebcb5331dc"
down_revision: Union[str, Sequence[str], None] = "ac3c23337782"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "BUDGET_THRESHOLD",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "BUDGET_THRESHOLD",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "CATEGORY",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "CATEGORY",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "FINANCIAL_PERIOD_SNAPSHOT",
        "category_spend",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "FINANCIAL_PERIOD_SNAPSHOT",
        "budget_status",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "FINANCIAL_PERIOD_SNAPSHOT",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "FINANCIAL_PERIOD_SNAPSHOT",
        "computed_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "NORMALIZED_TRANSACTION",
        "recurrence_period",
        existing_type=postgresql.ENUM("WEEKLY", "MONTHLY", "YEARLY", name="periodenum"),
        nullable=True,
    )
    op.alter_column(
        "NORMALIZED_TRANSACTION",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "NORMALIZED_TRANSACTION",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_NORMALIZED_TRANSACTION_category_id"), table_name="NORMALIZED_TRANSACTION")
    op.drop_constraint(op.f("NORMALIZED_TRANSACTION_category_id_fkey"), "NORMALIZED_TRANSACTION", type_="foreignkey")
    op.drop_column("NORMALIZED_TRANSACTION", "category_id")
    op.alter_column(
        "RAW_TRANSACTION",
        "raw_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "RAW_TRANSACTION",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "USER",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "USER",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "USER",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "USER",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "RAW_TRANSACTION",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "RAW_TRANSACTION",
        "raw_data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.add_column("NORMALIZED_TRANSACTION", sa.Column("category_id", sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        op.f("NORMALIZED_TRANSACTION_category_id_fkey"), "NORMALIZED_TRANSACTION", "CATEGORY", ["category_id"], ["id"]
    )
    op.create_index(
        op.f("ix_NORMALIZED_TRANSACTION_category_id"), "NORMALIZED_TRANSACTION", ["category_id"], unique=False
    )
    op.alter_column(
        "NORMALIZED_TRANSACTION",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "NORMALIZED_TRANSACTION",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "NORMALIZED_TRANSACTION",
        "recurrence_period",
        existing_type=postgresql.ENUM("WEEKLY", "MONTHLY", "YEARLY", name="periodenum"),
        nullable=False,
    )
    op.alter_column(
        "FINANCIAL_PERIOD_SNAPSHOT",
        "computed_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "FINANCIAL_PERIOD_SNAPSHOT",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "FINANCIAL_PERIOD_SNAPSHOT",
        "budget_status",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "FINANCIAL_PERIOD_SNAPSHOT",
        "category_spend",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "CATEGORY",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "CATEGORY",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "BUDGET_THRESHOLD",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "BUDGET_THRESHOLD",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
