from pydantic import BaseModel


class BaseIntentData(BaseModel):
    clarify: bool
    confidence: float | None = None
    missing: list[str] = []  # list of missing fields to clarify from user
    request_to_user: str | None = None  # request generated by LLM to clarify some data
    use_current_date: bool = False # a field to specify that transaction date is today
